from __future__ import annotations

from datetime import datetime

from .models import ProcessedPaper, RunSummary



def render_markdown_report(
    summary: RunSummary,
    papers_with_award: list[ProcessedPaper],
    papers_without_award: list[ProcessedPaper],
    *,
    include_missing_section: bool = True,
) -> str:
    lines: list[str] = []

    lines.append("# Ledger AI-MI Publication Report")
    lines.append("")
    lines.append(f"Generated: {summary.run_finished_at}")
    lines.append("")
    lines.append("## Run Summary")
    lines.append(f"- Team members scraped: {summary.team_member_count}")
    lines.append(f"- Team members resolved (DBLP/OpenAlex): {summary.resolved_member_count}")
    lines.append(f"- Team members unresolved in DBLP: {summary.unresolved_member_count}")
    lines.append(f"- Members with OpenAlex profile data: {summary.openalex_member_count}")
    lines.append(f"- DBLP publication fetch failures: {summary.publication_error_count}")
    lines.append(f"- Papers examined: {summary.examined_paper_count}")
    lines.append(f"- New papers this run: {summary.new_paper_count}")
    lines.append(f"- Papers scanned this run: {summary.processed_paper_count}")
    lines.append(f"- Scan failures (PDF/download/extract): {summary.scan_failure_count}")
    lines.append(f"- New papers with award mention: {summary.with_award_count}")
    lines.append(f"- New papers without award mention: {summary.missing_award_count}")
    lines.append("")

    lines.append("## New Papers With Award Mention")
    lines.append("")
    if not papers_with_award:
        lines.append("- None found in this run.")
    else:
        for idx, item in enumerate(papers_with_award, start=1):
            pub = item.publication
            year = pub.year if pub.year is not None else "n/a"
            venue = pub.venue or "unknown venue"
            links = []
            if pub.dblp_record_url:
                links.append(f"DBLP: {pub.dblp_record_url}")
            if item.chosen_pdf_url:
                links.append(f"PDF: {item.chosen_pdf_url}")
            mentions = ", ".join(item.award_mentions)
            lines.append(
                f"{idx}. **{pub.title}** ({year}, {venue}) | AIMI authors: {', '.join(pub.aimi_authors)} | mention(s): `{mentions}`"
            )
            if links:
                lines.append(f"   {' | '.join(links)}")

    if include_missing_section:
        lines.append("")
        lines.append("## New Papers Missing Award Mention")
        lines.append("")
        if not papers_without_award:
            lines.append("- None found in this run.")
        else:
            for idx, item in enumerate(papers_without_award, start=1):
                pub = item.publication
                year = pub.year if pub.year is not None else "n/a"
                venue = pub.venue or "unknown venue"
                lines.append(
                    f"{idx}. **{pub.title}** ({year}, {venue}) | AIMI authors: {', '.join(pub.aimi_authors)}"
                )
                if pub.dblp_record_url:
                    lines.append(f"   DBLP: {pub.dblp_record_url}")
                if item.chosen_pdf_url:
                    lines.append(f"   PDF: {item.chosen_pdf_url}")
                if item.pdf_download_error:
                    lines.append(f"   PDF error: {item.pdf_download_error}")

    lines.append("")
    lines.append("## Notes")
    lines.append("- Matching is exact/flexible string matching for award variants and the number `2433348`.")
    if not include_missing_section:
        lines.append("- This report is configured to include matched papers only.")
    lines.append("- PDF/A conversion only runs for papers where an award mention is detected and a PDF was downloaded.")
    lines.append(f"- Report generated by Ledger at {datetime.now().isoformat()}.")

    return "\n".join(lines) + "\n"
